# Generated by Django 4.1.2 on 2022-12-04 13:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Artisans', '0008_artisanenquiry_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_ref', models.CharField(max_length=255, null=True)),
                ('payment_date', models.DateTimeField(auto_now=True)),
                ('payment_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_request_endpoint', models.CharField(max_length=50)),
                ('payment_request_response', models.TextField(null=True)),
                ('payment_status', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Payment Requests Log',
                'verbose_name_plural': 'Payment Requests Log',
                'db_table': 'payment_log',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='TransactionModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateTimeField(auto_now_add=True)),
                ('transaction_type', models.CharField(choices=[(1, 'Wallet Funding'), (2, 'Debit'), (3, 'Payment Recieved')], max_length=10)),
                ('payment_channel', models.CharField(choices=[('Card', 'Card'), ('Transfer', 'Transfer'), ('Wallet', 'Wallet'), ('Ussd', 'Ussd'), ('Paystack', 'Paystack'), ('Flutterwave', 'Flutterwave'), ('Cash', 'Cash')], max_length=255)),
                ('transaction_reference', models.CharField(max_length=100)),
                ('transaction_description', models.CharField(max_length=255)),
                ('transaction_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('transaction_status', models.CharField(choices=[(1, 'Failed'), (2, 'Success'), (3, 'Processing')], max_length=255, null=True)),
                ('is_artisan', models.BooleanField(default=False)),
                ('transaction_artisan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Artisans.artisanmodel')),
                ('transaction_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transactions',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
                'managed': True,
            },
        ),
    ]
