# Generated by Django 4.1.2 on 2022-11-03 06:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailNotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254)),
                ('country', models.CharField(max_length=255, null=True)),
                ('subject', models.CharField(max_length=50, null=True)),
                ('message', models.CharField(max_length=255, null=True)),
                ('email_type', models.CharField(choices=[('1', 'User Registration Welcome'), ('2', 'Email Verification'), ('3', 'Merchant Team Invite')], max_length=255)),
                ('extra_data', models.CharField(max_length=1000, null=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('sent', models.BooleanField(default=True)),
                ('checked', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Email Notifications',
                'verbose_name_plural': 'Email Notifications',
                'db_table': 'email_notifications',
                'managed': True,
            },
        ),
    ]
