# Generated by Django 4.1.2 on 2022-11-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Notification', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailnotificationmodel',
            name='html_message',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
