# Generated by Django 4.1.2 on 2022-11-05 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Notification', '0002_emailnotificationmodel_html_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='SMSNotificationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=255, null=True)),
                ('message', models.TextField(null=True)),
                ('time', models.DateTimeField(auto_now=True)),
                ('sent', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'SMS Notifications',
                'verbose_name_plural': 'SMS Notifications',
                'db_table': 'sms_notifications',
                'managed': True,
            },
        ),
    ]
