# Generated by Django 4.1.2 on 2022-11-03 06:45

import Auth.api.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=255, null=True, unique=True, verbose_name='email address')),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True)),
                ('password', models.CharField(max_length=255)),
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, null=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('middle_name', models.CharField(blank=True, max_length=255, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.CharField(blank=True, max_length=255, null=True)),
                ('longitude', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='user/profile/')),
                ('gender', models.CharField(blank=True, choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, null=True)),
                ('wallet_balance', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=20, null=True)),
                ('country', models.CharField(blank=True, choices=[('Nigeria', 'Nigeria')], max_length=20, null=True)),
                ('country_code', models.CharField(blank=True, max_length=20, null=True)),
                ('public_key', models.CharField(blank=True, max_length=255, null=True)),
                ('secret_key', models.CharField(blank=True, max_length=255, null=True)),
                ('currency', models.CharField(blank=True, choices=[('NGN', 'NGN'), ('USD', 'USD')], max_length=20, null=True)),
                ('has_updated_profile', models.BooleanField(default=False)),
                ('has_updated_bank_info', models.BooleanField(default=False)),
                ('has_added_card', models.BooleanField(default=False)),
                ('registration_token', models.CharField(blank=True, max_length=20, null=True)),
                ('referral_code', models.CharField(blank=True, default=Auth.api.utils.generate_referral_id, max_length=20, null=True, unique=True)),
                ('email_activated', models.BooleanField(default=False)),
                ('is_artisan', models.BooleanField(default=False)),
                ('is_agent', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'User',
                'db_table': 'users',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ApiKey',
            fields=[
                ('id', models.CharField(editable=False, max_length=150, primary_key=True, serialize=False, unique=True)),
                ('prefix', models.CharField(editable=False, max_length=8, unique=True)),
                ('hashed_key', models.CharField(editable=False, max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('name', models.CharField(default=None, help_text='A free-form name for the API key. Need not be unique. 50 characters max.', max_length=50)),
                ('revoked', models.BooleanField(blank=True, default=False, help_text='If the API key is revoked, clients cannot use it anymore. (This cannot be undone.)')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='Once API key expires, clients cannot use it anymore.', null=True, verbose_name='Expires')),
                ('is_agent', models.BooleanField(default=False)),
                ('is_artisan', models.BooleanField(default=False)),
                ('is_user', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='api_keys', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'API Key',
                'verbose_name_plural': 'API Keys',
                'db_table': 'api_keys',
                'ordering': ('-created',),
                'abstract': False,
                'managed': True,
            },
        ),
    ]
