# Generated by Django 4.1.2 on 2022-11-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Auth', '0002_user_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, help_text='Contact phone number', max_length=20, null=True, unique=True),
        ),
    ]
