# Generated by Django 4.1.2 on 2022-11-05 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtisanModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artisan_id', models.CharField(default=uuid.uuid4, max_length=100, unique=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('state', models.CharField(default='', max_length=100)),
                ('state_code', models.CharField(default='', max_length=100)),
                ('country', models.CharField(choices=[('NG', 'Nigeria')], default='', max_length=100)),
                ('description', models.CharField(default='', max_length=255)),
                ('long_description', models.TextField(default='')),
                ('tagline', models.CharField(default='', max_length=255)),
                ('website', models.CharField(default='', max_length=255)),
                ('logo', models.ImageField(null=True, upload_to='')),
                ('phone', models.CharField(default='', max_length=255)),
                ('email', models.CharField(default='', max_length=255)),
                ('artisan_type', models.CharField(choices=[('1', 'PARTNEER'), ('2', 'INTEGRATIONS')], default='1', max_length=255)),
                ('latitude', models.CharField(default='', max_length=25)),
                ('longitude', models.CharField(default='', max_length=25)),
                ('working_time_from', models.TimeField(null=True)),
                ('working_time_to', models.TimeField(null=True)),
                ('wallet_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('pending_wallet_balance', models.DecimalField(decimal_places=2, default=0.0, max_digits=12)),
                ('public_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('secret_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('currency', models.CharField(choices=[('NGN', 'NGN'), ('USD', 'USD')], default='NGN', max_length=100)),
                ('email_activated', models.BooleanField(default=False)),
                ('cancelled_order', models.IntegerField(blank=True, null=True)),
                ('is_visible', models.BooleanField(default=True)),
                ('rc_number', models.CharField(blank=True, max_length=100, null=True)),
                ('email_activation_token', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('has_set_rate', models.BooleanField(blank=True, default=False)),
                ('has_set_profile', models.BooleanField(default=False)),
                ('has_added_asset', models.BooleanField(default=False)),
                ('has_added_team', models.BooleanField(default=False)),
                ('business_url', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('twitter_username', models.CharField(max_length=255, null=True)),
                ('instagram_username', models.CharField(max_length=255, null=True)),
                ('facebook_username', models.CharField(max_length=255, null=True)),
                ('tiktok_username', models.CharField(max_length=255, null=True)),
                ('available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('joined_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Artisan',
                'verbose_name_plural': 'Artisans',
                'db_table': 'artisans',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='ArtisanUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_address', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=255, null=True)),
                ('permission', models.CharField(choices=[('1', 'Business Owner'), ('2', 'Admin'), ('3', 'Staff'), ('4', 'Customer Support')], max_length=50)),
                ('invitation_accepted', models.BooleanField(blank=True, default=True)),
                ('invite_token', models.CharField(default=uuid.uuid4, editable=False, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artisans.artisanmodel')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Artisan User',
                'verbose_name_plural': 'Artisan Users',
                'db_table': 'artisans_users',
                'managed': True,
            },
        ),
    ]
