# Generated by Django 4.1.2 on 2022-11-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artisans', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisanmodel',
            name='country',
            field=models.CharField(blank=True, choices=[('NG', 'Nigeria')], default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artisanmodel',
            name='description',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artisanmodel',
            name='latitude',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='artisanmodel',
            name='long_description',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='artisanmodel',
            name='longitude',
            field=models.CharField(blank=True, default='', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='artisanmodel',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artisanmodel',
            name='state_code',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='artisanmodel',
            name='tagline',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artisanmodel',
            name='website',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
