# Generated by Django 4.1.2 on 2022-11-19 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Job', '0001_initial'),
        ('Artisans', '0002_alter_artisanmodel_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artisanmodel',
            name='available',
        ),
        migrations.AddField(
            model_name='artisanmodel',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artisanmodel',
            name='profession',
            field=models.ManyToManyField(to='Job.professionmodel'),
        ),
        migrations.AddField(
            model_name='artisanmodel',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Available'), ('BUSY', 'Busy'), ('CLOSED', 'Closed')], default='AVAILABLE', max_length=100),
        ),
    ]
