# Generated by Django 4.1.2 on 2022-11-23 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artisans', '0004_alter_artisanmodel_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artisanmodel',
            name='facebook_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artisanmodel',
            name='instagram_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artisanmodel',
            name='tiktok_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artisanmodel',
            name='twitter_username',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
