# Generated by Django 4.1.2 on 2022-12-02 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Artisans', '0006_artisanmodel_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtisanEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('artisan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Artisans.artisanmodel')),
            ],
            options={
                'verbose_name': 'Artisan Enquiry',
                'verbose_name_plural': 'Artisan Enquiries',
                'db_table': 'artisan_enquiry',
                'managed': True,
            },
        ),
    ]
