# Generated by Django 4.1.2 on 2022-12-03 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artisans', '0007_artisanenquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanenquiry',
            name='date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
