# Generated by Django 4.1.2 on 2022-12-06 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artisans', '0008_artisanenquiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanenquiry',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='artisanenquiry',
            name='created_at',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='artisanenquiry',
            name='time',
            field=models.TimeField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='artisanenquiry',
            name='date',
            field=models.DateField(max_length=255, null=True),
        ),
    ]
