# Generated by Django 4.1.2 on 2022-12-06 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artisans', '0009_artisanenquiry_address_artisanenquiry_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artisanenquiry',
            name='response',
            field=models.CharField(choices=[('ACCEPT', 'Accept'), ('PENDING', 'Pending'), ('REJECT', 'Reject')], default='PENDING', max_length=255),
        ),
    ]
