# Generated by Django 4.1.2 on 2022-12-19 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Artisans', '0011_artisanprofession'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name': 'Agent',
                'verbose_name_plural': 'Agents',
                'db_table': 'agents',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='artisanmodel',
            name='agent',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='artisanmodel',
            name='rank',
            field=models.CharField(choices=[('5', 'Gold'), ('4', 'Silver'), ('3', 'Bronze'), ('2', 'Standard'), ('1', 'Basic')], default='1', max_length=50),
        ),
    ]
